import { getDb } from "../api/queries/connection";
import * as schema from "./schema";

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  const existingRows = await db.select().from(schema.explorePlaces);
  const existingNames = new Set(existingRows.map((r) => r.name));

  await db.insert(schema.explorePlaces).values([
    // ── Kyoto ──
    { name: "Fushimi Inari Shrine", city: "Kyoto", country: "Japan", lat: 34.9671, lng: 135.7727, category: "activity", tags: ["temple", "iconic", "hike"], styles: ["historical", "adventure"], rating: 4.8, priceLevel: 1, image: "/place-temple.jpg", description: "Thousands of vermilion torii gates winding up the mountain, go at dawn to beat the crowds.", hidden: false },
    { name: "Ichiran Ramen", city: "Kyoto", country: "Japan", lat: 35.0037, lng: 135.7687, category: "food", tags: ["ramen", "solo-dining", "late-night"], styles: ["food", "budget"], rating: 4.6, priceLevel: 1, image: "/place-ramen.jpg", description: "Cult tonkotsu ramen bar with individual booths and a customisable broth sheet.", hidden: false },
    { name: "Arashiyama Bamboo Grove", city: "Kyoto", country: "Japan", lat: 35.0170, lng: 135.6713, category: "activity", tags: ["nature", "walk", "iconic"], styles: ["relaxing", "adventure"], rating: 4.7, priceLevel: 1, image: "/place-hike.jpg", description: "Towering bamboo corridor on the city's western edge, best paired with the Hozugawa river.", hidden: false },
    { name: "Kissa Master", city: "Kyoto", country: "Japan", lat: 35.0095, lng: 135.7603, category: "food", tags: ["coffee", "kissaten", "quiet"], styles: ["relaxing", "food"], rating: 4.9, priceLevel: 2, image: "/place-cafe.jpg", description: "A six-seat kissaten where the owner hand-whisks matcha in near silence. Cash only.", hidden: true },
    { name: "Gion Tanto", city: "Kyoto", country: "Japan", lat: 35.0036, lng: 135.7750, category: "food", tags: ["izakaya", "okonomiyaki", "dinner"], styles: ["food", "budget"], rating: 4.5, priceLevel: 2, image: "/place-market.jpg", description: "Lively counter-seating okonomiyaki spot beloved by locals in the heart of Gion.", hidden: true },
    { name: "Bar K6", city: "Kyoto", country: "Japan", lat: 35.0049, lng: 135.7705, category: "food", tags: ["cocktails", "nightlife", "whisky"], styles: ["food", "relaxing"], rating: 4.7, priceLevel: 3, image: "/place-bar.jpg", description: "Moody second-floor whisky bar with one of the best Japanese bottle lists in the city.", hidden: true },
    { name: "Kyoto National Museum", city: "Kyoto", country: "Japan", lat: 34.9899, lng: 135.7735, category: "activity", tags: ["museum", "art", "history"], styles: ["historical"], rating: 4.5, priceLevel: 2, image: "/place-museum.jpg", description: "Heian-era treasures and rotating special exhibitions in a Meiji brick hall.", hidden: false },
    // ── Osaka / Nara ──
    { name: "Dotonbori Street Food Crawl", city: "Osaka", country: "Japan", lat: 34.6687, lng: 135.5013, category: "food", tags: ["street-food", "takoyaki", "neon"], styles: ["food", "budget", "adventure"], rating: 4.6, priceLevel: 1, image: "/explore-street.jpg", description: "Takoyaki, kushikatsu and crab under the Glico sign. Japan's kitchen at full volume.", hidden: false },
    { name: "Nara Deer Park", city: "Nara", country: "Japan", lat: 34.6851, lng: 135.8430, category: "activity", tags: ["nature", "deer", "temple"], styles: ["adventure", "historical"], rating: 4.7, priceLevel: 1, image: "/place-temple.jpg", description: "Bow for shika senbei crackers from 1,200 free-roaming deer, then continue to Todai-ji.", hidden: false },
    // ── Lisbon ──
    { name: "Alfama Sunrise Walk", city: "Lisbon", country: "Portugal", lat: 38.7115, lng: -9.1257, category: "activity", tags: ["walk", "viewpoint", "old-town"], styles: ["relaxing", "historical"], rating: 4.8, priceLevel: 1, image: "/cover-lisbon.jpg", description: "Miradouro-to-miradouro stroll through the city's oldest maze of tiles and tram lines.", hidden: false },
    { name: "Time Out Market", city: "Lisbon", country: "Portugal", lat: 38.7072, lng: -9.1458, category: "food", tags: ["market", "seafood", "casual"], styles: ["food", "budget"], rating: 4.4, priceLevel: 2, image: "/place-market.jpg", description: "The city's best chefs under one roof, go off-peak and order the prego and pastéis.", hidden: false },
    // ── Amalfi ──
    { name: "Path of the Gods", city: "Positano", country: "Italy", lat: 40.6281, lng: 14.4850, category: "activity", tags: ["hike", "views", "nature"], styles: ["adventure"], rating: 4.9, priceLevel: 1, image: "/cover-amalfi.jpg", description: "Cliff-edge trail from Bomerano to Nocelle with the whole coast spread out below.", hidden: false },
    { name: "Da Adolfo Beach Shack", city: "Positano", country: "Italy", lat: 40.6210, lng: 14.4690, category: "food", tags: ["seafood", "beach", "lunch"], styles: ["food", "relaxing"], rating: 4.6, priceLevel: 2, image: "/place-ramen.jpg", description: "Reachable only by the little red boat, grilled mozzarella on lemon leaves since 1966.", hidden: true },
    // ── Marrakech ──
    { name: "Jardin Majorelle", city: "Marrakech", country: "Morocco", lat: 31.6417, lng: -8.0033, category: "activity", tags: ["garden", "design", "calm"], styles: ["relaxing", "historical"], rating: 4.6, priceLevel: 2, image: "/cover-marrakech.jpg", description: "Cobalt-blue villa and cactus garden, book the first slot of the day.", hidden: false },
    { name: "Medina Spice Souk", city: "Marrakech", country: "Morocco", lat: 31.6295, lng: -7.9860, category: "shopping", tags: ["souk", "spices", "haggling"], styles: ["adventure", "budget", "food"], rating: 4.5, priceLevel: 1, image: "/place-market.jpg", description: "Pyramids of ras el hanout and saffron; follow your nose and haggle with a smile.", hidden: false },
    // ── Patagonia ──
    { name: "Laguna de los Tres", city: "El Chaltén", country: "Argentina", lat: -49.2720, lng: -72.9660, category: "activity", tags: ["hike", "fitz-roy", "lake"], styles: ["adventure"], rating: 4.9, priceLevel: 1, image: "/cover-patagonia.jpg", description: "The classic Fitz Roy sunrise push: 10km, 750m of gain, worth every step.", hidden: false },
    // ── Reykjavik ──
    { name: "Reynisfjara Black Beach", city: "Vík", country: "Iceland", lat: 63.4055, lng: -19.0708, category: "activity", tags: ["beach", "basalt", "photography"], styles: ["adventure", "relaxing"], rating: 4.8, priceLevel: 1, image: "/cover-reykjavik.jpg", description: "Basalt columns and roaring Atlantic surf, respect the sneaker waves.", hidden: false },
    { name: "Sky Lagoon", city: "Reykjavik", country: "Iceland", lat: 64.1200, lng: -21.9300, category: "activity", tags: ["spa", "geothermal", "sunset"], styles: ["relaxing"], rating: 4.7, priceLevel: 3, image: "/place-onsen.jpg", description: "Oceanside geothermal infinity edge with the seven-step ritual. Sunset slots are magic.", hidden: false },
    // ── Copenhagen ──
    { name: "Nyhavn & Harbour Circle", city: "Copenhagen", country: "Denmark", lat: 55.6797, lng: 12.5900, category: "activity", tags: ["harbor", "bikes", "iconic"], styles: ["relaxing", "historical"], rating: 4.6, priceLevel: 1, image: "/cover-copenhagen.jpg", description: "Pastel facades, then a go-boat loop through Christianshavn's canals.", hidden: false },
    { name: "Torvehallerne Food Hall", city: "Copenhagen", country: "Denmark", lat: 55.6837, lng: 12.5698, category: "food", tags: ["smorrebrod", "market", "coffee"], styles: ["food"], rating: 4.5, priceLevel: 2, image: "/place-cafe.jpg", description: "Smørrebrød at Hallernes, a flat white at Coffee Collective, done.", hidden: false },
    // ── Oaxaca ──
    { name: "Mercado 20 de Noviembre", city: "Oaxaca", country: "Mexico", lat: 17.0594, lng: -96.7237, category: "food", tags: ["market", "mole", "mezcal"], styles: ["food", "budget", "adventure"], rating: 4.7, priceLevel: 1, image: "/cover-oaxaca.jpg", description: "Smoke-filled pasillo de carnes asadas, point, pay, feast. Mole negro after.", hidden: false },
    { name: "Hierve el Agua", city: "Oaxaca", country: "Mexico", lat: 16.8656, lng: -96.2764, category: "activity", tags: ["pools", "petrified-waterfall", "day-trip"], styles: ["adventure", "relaxing"], rating: 4.6, priceLevel: 1, image: "/place-hike.jpg", description: "Mineral infinity pools on a petrified waterfall, 90 minutes from the city.", hidden: false },
    // ── Tea ceremony ──
    { name: "Camellia Tea Ceremony", city: "Kyoto", country: "Japan", lat: 35.0116, lng: 135.7681, category: "activity", tags: ["tea", "culture", "small-group"], styles: ["relaxing", "historical"], rating: 4.9, priceLevel: 2, image: "/explore-tea.jpg", description: "An hour of quiet ritual in a Ninenzaka townhouse, whisk your own matcha.", hidden: true },
    // ── Expansion: deeper coverage per city (AI itinerary corpus) ──
    { name: "Belém Tower", city: "Lisbon", country: "Portugal", lat: 38.6916, lng: -9.2160, category: "activity", tags: ["monument", "riverfront", "iconic"], styles: ["historical"], rating: 4.6, priceLevel: 1, image: "/cover-lisbon.jpg", description: "Manueline fortress guarding the Tagus since 1519, pair with the monastery next door.", hidden: false },
    { name: "Pastéis de Belém", city: "Lisbon", country: "Portugal", lat: 38.6979, lng: -9.2032, category: "food", tags: ["bakery", "pastel-de-nata", "iconic"], styles: ["food", "budget"], rating: 4.7, priceLevel: 1, image: "/place-cafe.jpg", description: "The original custard tart since 1837, warm, with cinnamon, standing at the counter.", hidden: false },
    { name: "LX Factory", city: "Lisbon", country: "Portugal", lat: 38.7034, lng: -9.1787, category: "shopping", tags: ["design", "bookshops", "markets"], styles: ["adventure", "budget"], rating: 4.4, priceLevel: 2, image: "/place-market.jpg", description: "Industrial complex turned creative village. Ler Devagar bookshop is the highlight.", hidden: false },
    { name: "Park Bar Rooftop", city: "Lisbon", country: "Portugal", lat: 38.7110, lng: -9.1440, category: "food", tags: ["rooftop", "sunset", "drinks"], styles: ["relaxing", "food"], rating: 4.5, priceLevel: 2, image: "/place-bar.jpg", description: "On top of a car park, above the Bairro, the sunset view over the 25 de Abril bridge.", hidden: true },
    { name: "Bahia Palace", city: "Marrakech", country: "Morocco", lat: 31.6214, lng: -7.9825, category: "activity", tags: ["palace", "tilework", "gardens"], styles: ["historical"], rating: 4.6, priceLevel: 1, image: "/cover-marrakech.jpg", description: "Nineteenth-century vizier's palace of painted cedar and zellige courtyards.", hidden: false },
    { name: "Jemaa el-Fnaa at Dusk", city: "Marrakech", country: "Morocco", lat: 31.6258, lng: -7.9891, category: "activity", tags: ["square", "performers", "night"], styles: ["adventure", "food"], rating: 4.5, priceLevel: 1, image: "/explore-street.jpg", description: "The great square transforms at sunset, drummers, storytellers, grill smoke.", hidden: false },
    { name: "Le Jardin Secret", city: "Marrakech", country: "Morocco", lat: 31.6329, lng: -7.9880, category: "activity", tags: ["garden", "riad", "calm"], styles: ["relaxing", "historical"], rating: 4.5, priceLevel: 2, image: "/cover-marrakech.jpg", description: "A restored riad garden hidden in the mouassine, the tower view is worth the extra ticket.", hidden: true },
    { name: "Nomad Rooftop", city: "Marrakech", country: "Morocco", lat: 31.6316, lng: -7.9866, category: "food", tags: ["rooftop", "modern-moroccan", "dinner"], styles: ["food", "relaxing"], rating: 4.4, priceLevel: 2, image: "/place-ramen.jpg", description: "Modern Moroccan plates over the spice square, book the sunset seating.", hidden: false },
    { name: "Amalfi Cathedral", city: "Positano", country: "Italy", lat: 40.6346, lng: 14.6027, category: "activity", tags: ["cathedral", "piazza", "history"], styles: ["historical"], rating: 4.6, priceLevel: 1, image: "/cover-amalfi.jpg", description: "Striped Arab-Norman facade above the piazza, the cloister is the quiet part.", hidden: false },
    { name: "Villa Rufolo Gardens", city: "Positano", country: "Italy", lat: 40.6492, lng: 14.6117, category: "activity", tags: ["gardens", "ravello", "views"], styles: ["relaxing", "historical"], rating: 4.7, priceLevel: 2, image: "/cover-amalfi.jpg", description: "Wagner's inspiration in Ravello, umbrella pines over a sheer drop to the sea.", hidden: false },
    { name: "Chez Black", city: "Positano", country: "Italy", lat: 40.6280, lng: 14.4850, category: "food", tags: ["beachfront", "seafood", "dinner"], styles: ["food", "relaxing"], rating: 4.4, priceLevel: 3, image: "/place-ramen.jpg", description: "Feet-in-the-sand Positano institution, order the spaghetti with clams.", hidden: false },
    { name: "Tivoli Gardens", city: "Copenhagen", country: "Denmark", lat: 55.6736, lng: 12.5681, category: "activity", tags: ["gardens", "rides", "evening"], styles: ["relaxing", "adventure"], rating: 4.6, priceLevel: 2, image: "/cover-copenhagen.jpg", description: "1843 pleasure gardens, go at dusk when 100,000 lights come on.", hidden: false },
    { name: "Rosenborg Castle", city: "Copenhagen", country: "Denmark", lat: 55.6857, lng: 12.5773, category: "activity", tags: ["castle", "crown-jewels", "park"], styles: ["historical"], rating: 4.5, priceLevel: 2, image: "/place-museum.jpg", description: "Renaissance castle with the crown jewels, set in the King's Garden.", hidden: false },
    { name: "Reffen Street Food", city: "Copenhagen", country: "Denmark", lat: 55.6930, lng: 12.6070, category: "food", tags: ["street-food", "harbor", "casual"], styles: ["food", "budget"], rating: 4.5, priceLevel: 1, image: "/place-market.jpg", description: "Shipping-container food stalls on Refshaleøen, grab a deckchair on the water.", hidden: false },
    { name: "Monte Albán", city: "Oaxaca", country: "Mexico", lat: 17.0436, lng: -96.7674, category: "activity", tags: ["ruins", "zapotec", "views"], styles: ["historical", "adventure"], rating: 4.8, priceLevel: 1, image: "/cover-oaxaca.jpg", description: "Zapotec capital on a flattened mountaintop, arrive at opening for empty plazas.", hidden: false },
    { name: "Santo Domingo Church", city: "Oaxaca", country: "Mexico", lat: 17.0654, lng: -96.7234, category: "activity", tags: ["church", "gold", "ethnobotanic-garden"], styles: ["historical", "relaxing"], rating: 4.7, priceLevel: 1, image: "/cover-oaxaca.jpg", description: "Gilded baroque interior and the ethnobotanic garden behind. Oaxaca's heart.", hidden: false },
    { name: "Casa Oaxaca Rooftop", city: "Oaxaca", country: "Mexico", lat: 17.0606, lng: -96.7220, category: "food", tags: ["dinner", "mole", "rooftop"], styles: ["food"], rating: 4.6, priceLevel: 3, image: "/place-ramen.jpg", description: "The city's refined kitchen, seven-mole tasting as the church lights come on.", hidden: false },
    { name: "Mezcaloteca Tasting", city: "Oaxaca", country: "Mexico", lat: 17.0612, lng: -96.7250, category: "food", tags: ["mezcal", "tasting", "reservation"], styles: ["food", "adventure"], rating: 4.8, priceLevel: 2, image: "/place-bar.jpg", description: "Reservation-only library of rare agave spirits, a guided flight of five.", hidden: true },
    { name: "Hallgrímskirkja Tower", city: "Reykjavik", country: "Iceland", lat: 64.1417, lng: -21.9266, category: "activity", tags: ["church", "viewpoint", "iconic"], styles: ["historical", "relaxing"], rating: 4.6, priceLevel: 1, image: "/cover-reykjavik.jpg", description: "Ride the lift up the basalt-inspired tower for the city's best panorama.", hidden: false },
    { name: "Þingvellir National Park", city: "Reykjavik", country: "Iceland", lat: 64.2559, lng: -21.1299, category: "activity", tags: ["tectonic-rift", "golden-circle", "day-trip"], styles: ["adventure", "historical"], rating: 4.7, priceLevel: 1, image: "/place-hike.jpg", description: "Walk between two continental plates at the site of the world's oldest parliament.", hidden: false },
    { name: "Reykjadalur Hot River", city: "Reykjavik", country: "Iceland", lat: 64.0233, lng: -21.1930, category: "activity", tags: ["hike", "hot-spring", "river"], styles: ["adventure", "relaxing"], rating: 4.8, priceLevel: 1, image: "/place-onsen.jpg", description: "A 45-minute valley hike to a steaming river you can bathe in. Bring a towel.", hidden: true },
    { name: "Bæjarins Beztu Pylsur", city: "Reykjavik", country: "Iceland", lat: 64.1419, lng: -21.9420, category: "food", tags: ["hot-dog", "late-night", "iconic"], styles: ["food", "budget"], rating: 4.4, priceLevel: 1, image: "/place-market.jpg", description: "Iceland's famous lamb hot dog stand, order 'eina með öllu' (one with everything).", hidden: false },
    { name: "Laguna Torre", city: "El Chaltén", country: "Argentina", lat: -49.2963, lng: -73.0040, category: "activity", tags: ["hike", "glacier", "lake"], styles: ["adventure"], rating: 4.8, priceLevel: 1, image: "/cover-patagonia.jpg", description: "The gentler big hike. Cerro Torre spires over a milky glacial lagoon.", hidden: false },
    { name: "Chorrillo del Salto", city: "El Chaltén", country: "Argentina", lat: -49.3160, lng: -72.9050, category: "activity", tags: ["waterfall", "easy-walk", "picnic"], styles: ["relaxing", "adventure"], rating: 4.5, priceLevel: 1, image: "/place-hike.jpg", description: "A flat 4km amble to a waterfall, the rest-day reward.", hidden: false },
    { name: "La Vineria", city: "El Chaltén", country: "Argentina", lat: -49.3310, lng: -72.8860, category: "food", tags: ["wine-bar", "patagonian", "dinner"], styles: ["food", "relaxing"], rating: 4.6, priceLevel: 2, image: "/place-bar.jpg", description: "Tiny wine bar with Patagonian lamb and an Argentine list, book ahead.", hidden: true },
    { name: "Osaka Castle", city: "Osaka", country: "Japan", lat: 34.6873, lng: 135.5262, category: "activity", tags: ["castle", "park", "iconic"], styles: ["historical"], rating: 4.5, priceLevel: 1, image: "/place-temple.jpg", description: "Moated 16th-century keep, the park is best in cherry season.", hidden: false },
    { name: "Kuromon Ichiba Market", city: "Osaka", country: "Japan", lat: 34.6654, lng: 135.5065, category: "food", tags: ["market", "seafood", "lunch"], styles: ["food", "budget"], rating: 4.5, priceLevel: 2, image: "/place-market.jpg", description: "Osaka's kitchen counter, scallops, uni, and wagyu skewers eaten standing.", hidden: false },
    { name: "Shinsekai & Tsutenkaku", city: "Osaka", country: "Japan", lat: 34.6525, lng: 135.5063, category: "activity", tags: ["retro", "tower", "kushikatsu"], styles: ["adventure", "budget"], rating: 4.4, priceLevel: 1, image: "/explore-street.jpg", description: "Retro-Showa streets under the tower, kushikatsu with the no-double-dipping rule.", hidden: false },
    { name: "Todai-ji Great Buddha", city: "Nara", country: "Japan", lat: 34.6889, lng: 135.8398, category: "activity", tags: ["temple", "buddha", "iconic"], styles: ["historical"], rating: 4.8, priceLevel: 1, image: "/place-temple.jpg", description: "The world's largest bronze Buddha inside the world's largest wooden hall.", hidden: false },
    { name: "Isuien Garden", city: "Nara", country: "Japan", lat: 34.6851, lng: 135.8360, category: "activity", tags: ["garden", "tea", "quiet"], styles: ["relaxing"], rating: 4.6, priceLevel: 2, image: "/explore-tea.jpg", description: "Borrowed-scenery strolling garden most visitors walk straight past.", hidden: true },
    { name: "Skógafoss", city: "Vík", country: "Iceland", lat: 63.5321, lng: -19.5114, category: "activity", tags: ["waterfall", "rainbow", "south-coast"], styles: ["adventure"], rating: 4.8, priceLevel: 1, image: "/cover-reykjavik.jpg", description: "A 60m curtain of water you can walk right up to, stairs to the top too.", hidden: false },
    { name: "Dyrhólaey Arch", city: "Vík", country: "Iceland", lat: 63.4028, lng: -19.1265, category: "activity", tags: ["arch", "puffins", "viewpoint"], styles: ["adventure", "relaxing"], rating: 4.6, priceLevel: 1, image: "/cover-reykjavik.jpg", description: "The sea-arch promontory west of Vík, puffins in summer, huge surf always.", hidden: false },
  ].filter((p) => !existingNames.has(p.name)));

  console.log("Seed complete.");

  console.log("Done.");
  process.exit(0);
}

seed();
